### ISSUE TITLE
visualizer not working in Weka

### ISSUE THREAD

**Issue by rsalvini** [fracpete/graphviz-treevisualize-weka-package#3]
Hi,
The visualizer is not working for me in Weka.
I already created the `$HOME/wekafiles/props/GraphVizTreeVisualization.props` with the content `Executable=/usr/bin/dot`, and I guess I followed all the instructions steps in the README file.

My OS is Ubuntu 14.04 and I'm using Weka 3-8-1.

That's the error that appears in the terminal window when I try to use the visualizer for a decision tree:

```
Exception in thread "AWT-EventQueue-0" java.lang.IllegalArgumentException: Width (-1) and height (-1) cannot be <= 0
	java.awt.image.DirectColorModel.createCompatibleWritableRaster(DirectColorModel.java:1016)
	java.awt.image.BufferedImage.<init>(BufferedImage.java:333)
	weka.gui.visualize.plugins.GraphVizTreeVisualization.toBufferedImage(GraphVizTreeVisualization.java:167)
	weka.gui.visualize.plugins.GraphVizPanel.setDotty(GraphVizPanel.java:63)
	weka.gui.visualize.plugins.GraphVizTreeVisualizationPlugin$1.actionPerformed(GraphVizTreeVisualizationPlugin.java:64)
	javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:2022)
	javax.swing.AbstractButton$Handler.actionPerformed(AbstractButton.java:2348)
	javax.swing.DefaultButtonModel.fireActionPerformed(DefaultButtonModel.java:402)
	javax.swing.DefaultButtonModel.setPressed(DefaultButtonModel.java:259)
	javax.swing.AbstractButton.doClick(AbstractButton.java:376)
	javax.swing.plaf.basic.BasicMenuItemUI.doClick(BasicMenuItemUI.java:833)
	javax.swing.plaf.basic.BasicMenuItemUI$Handler.mouseReleased(BasicMenuItemUI.java:877)
	java.awt.Component.processMouseEvent(Component.java:6533)
	javax.swing.JComponent.processMouseEvent(JComponent.java:3324)
	java.awt.Component.processEvent(Component.java:6298)
	java.awt.Container.processEvent(Container.java:2236)
	java.awt.Component.dispatchEventImpl(Component.java:4889)
	java.awt.Container.dispatchEventImpl(Container.java:2294)
	java.awt.Component.dispatchEvent(Component.java:4711)
	java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4888)
	java.awt.LightweightDispatcher.processMouseEvent(Container.java:4525)
	java.awt.LightweightDispatcher.dispatchEvent(Container.java:4466)
	java.awt.Container.dispatchEventImpl(Container.java:2280)
	java.awt.Window.dispatchEventImpl(Window.java:2746)
	java.awt.Component.dispatchEvent(Component.java:4711)
	java.awt.EventQueue.dispatchEventImpl(EventQueue.java:758)
	java.awt.EventQueue.access$500(EventQueue.java:97)
	java.awt.EventQueue$3.run(EventQueue.java:709)
	java.awt.EventQueue$3.run(EventQueue.java:703)
	java.security.AccessController.doPrivileged(Native Method)
	java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
	java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:90)
	java.awt.EventQueue$4.run(EventQueue.java:731)
	java.awt.EventQueue$4.run(EventQueue.java:729)
	java.security.AccessController.doPrivileged(Native Method)
	java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
	java.awt.EventQueue.dispatchEvent(EventQueue.java:728)
	java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	java.awt.EventDispatchThread.run(EventDispatchThread.java:82)

	at java.awt.image.DirectColorModel.createCompatibleWritableRaster(DirectColorModel.java:1016)
	at java.awt.image.BufferedImage.<init>(BufferedImage.java:333)
	at weka.gui.visualize.plugins.GraphVizTreeVisualization.toBufferedImage(GraphVizTreeVisualization.java:167)
	at weka.gui.visualize.plugins.GraphVizPanel.setDotty(GraphVizPanel.java:63)
	at weka.gui.visualize.plugins.GraphVizTreeVisualizationPlugin$1.actionPerformed(GraphVizTreeVisualizationPlugin.java:64)
	at javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:2022)
	at javax.swing.AbstractButton$Handler.actionPerformed(AbstractButton.java:2348)
	at javax.swing.DefaultButtonModel.fireActionPerformed(DefaultButtonModel.java:402)
	at javax.swing.DefaultButtonModel.setPressed(DefaultButtonModel.java:259)
	at javax.swing.AbstractButton.doClick(AbstractButton.java:376)
	at javax.swing.plaf.basic.BasicMenuItemUI.doClick(BasicMenuItemUI.java:833)
	at javax.swing.plaf.basic.BasicMenuItemUI$Handler.mouseReleased(BasicMenuItemUI.java:877)
	at java.awt.Component.processMouseEvent(Component.java:6533)
	at javax.swing.JComponent.processMouseEvent(JComponent.java:3324)
	at java.awt.Component.processEvent(Component.java:6298)
	at java.awt.Container.processEvent(Container.java:2236)
	at java.awt.Component.dispatchEventImpl(Component.java:4889)
	at java.awt.Container.dispatchEventImpl(Container.java:2294)
	at java.awt.Component.dispatchEvent(Component.java:4711)
	at java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4888)
	at java.awt.LightweightDispatcher.processMouseEvent(Container.java:4525)
	at java.awt.LightweightDispatcher.dispatchEvent(Container.java:4466)
	at java.awt.Container.dispatchEventImpl(Container.java:2280)
	at java.awt.Window.dispatchEventImpl(Window.java:2746)
	at java.awt.Component.dispatchEvent(Component.java:4711)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:758)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.awt.EventQueue$3.run(EventQueue.java:703)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:90)
	at java.awt.EventQueue$4.run(EventQueue.java:731)
	at java.awt.EventQueue$4.run(EventQueue.java:729)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:728)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
```

Any tips to solve this problem?

Thank you.

**Comment by fracpete** [comment]
On Linux you don't need to create the `.props` file, as the `dot` executable is on the path. I just tried the plugin on the UCI dataset *anneal* with default J48 and it worked fine. Can you try this on your machine?
The above error occurs when trying to convert the loaded image in order to display it. A size of -1 x -1 indicates that something went wrong loading the PNG file generated by graphviz/dot.
Does Weka's default tree visualization display the tree? How large is the tree?

**Comment by rsalvini** [comment]
I was using the _iris_ and _weather_ databases of data directory of weka to test the package. The weka's default j48 displays both trees, which are small.
I tried the package on other machine (also with Ubuntu) and the same issue occurred.

**Comment by fracpete** [comment]
Can you verify that these commands generate an `iris.png` plot for you?
```
java -cp weka.jar weka.classifiers.trees.J48 -t iris.arff -g > iris.dot
dot iris.dot -T png -o iris.png
```
**NB:** You may have to adjust paths to jar, dataset and output files.

**Comment by rsalvini** [comment]
Yes it works.
Indeed, I usually use these command line to generate the tree using dot, and I was interested in the package, just because I could do it now from the Weka's GUI.

**Comment by fracpete** [comment]
That's weird. The plugin basically just retrieves the tree generated by the classifier, saves it in a temporary file, calls the `dot` executable to generate a PNG and then loads the PNG.
Do you have any other plugins beside this one installed? Are you using an Oracle Java SE or OpenJDK?

**Comment by rsalvini** [comment]
yeah! I don't know what is going on here.
I tested it in a third computer (with Ubuntu 16.04, Weka 3-8-1 and openjdk version "1.8.0_121") and the same problem happened.
I'm not using any other plugin.
:(

**Comment by rsalvini** [comment]
In which directory the png file is generated by the visualization plugin?

**Comment by fracpete** [comment]
Try using an Oracle JDK (recommended for Weka), as I've had weird behavior with OpenJDK in the past.

**Comment by fracpete** [comment]
Temp directory in use: System.getProperty("java.io.tmpdir"). This should be `/tmp` on a Linux system. The temp files (dot and png) get deleted immediately again after loading the PNG.

**Comment by rsalvini** [comment]
I observed the `/tmp` when I was running the visualize. 
It creates the `dot` file correctly (e.g. `gvtv12d.dot`), but not the `png` file (`gvtv12d.png` is created but with just a few kB).
If I execute the command `dot gvtv12d.dot -T png -o gvtv12d.png` in a terminal directly in `/tmp`, it generates the `png` correctly.

**Comment by rsalvini** [comment]
A weird thing is that the content of the `png` file that visualize is generating is dot commands
These are the files that visualize created for the tree of iris dataset:

**- gvtv12d.dot:** (this is OK)
```
digraph J48Tree {
N0 [label="petalwidth" ]
N0->N1 [label="<= 0.6"]
N1 [label="Iris-setosa (50.0)" shape=box style=filled ]
N0->N2 [label="> 0.6"]
N2 [label="petalwidth" ]
N2->N3 [label="<= 1.7"]
N3 [label="petallength" ]
N3->N4 [label="<= 4.9"]
N4 [label="Iris-versicolor (48.0/1.0)" shape=box style=filled ]
N3->N5 [label="> 4.9"]
N5 [label="petalwidth" ]
N5->N6 [label="<= 1.5"]
N6 [label="Iris-virginica (3.0)" shape=box style=filled ]
N5->N7 [label="> 1.5"]
N7 [label="Iris-versicolor (3.0/1.0)" shape=box style=filled ]
N2->N8 [label="> 1.7"]
N8 [label="Iris-virginica (46.0/1.0)" shape=box style=filled ]
}


```

**- gvtv12d.png:** (this is the problem)

```
digraph J48Tree {
	graph [bb="0,0,363.5,384"];
	node [label="\N"];
	N0	 [height=0.5,
		label=petalwidth,
		pos="120.5,366",
		width=1.336];
	N1	 [height=0.5,
		label="Iris-setosa (50.0)",
		pos="75.5,279",
		shape=box,
		style=filled,
		width=1.5139];
	N0 -> N1	 [label="<= 0.6",
		lp="120.5,322.5",
		pos="e,84.526,297.05 111.61,348.21 105.24,336.18 96.543,319.75 89.279,306.03"];
	N2	 [height=0.5,
		label=petalwidth,
		pos="196.5,279",
		width=1.336];
	N0 -> N2	 [label="> 0.6",
		lp="178.5,322.5",
		pos="e,181.89,296.34 135.15,348.61 146.51,335.91 162.4,318.13 175.17,303.86"];
	N3	 [height=0.5,
		label=petallength,
		pos="105.5,192",
		width=1.3902];
	N2 -> N3	 [label="<= 1.7",
		lp="175.5,235.5",
		pos="e,122.85,209.21 179.38,262.01 165.62,249.15 146.08,230.9 130.55,216.4"];
	N8	 [height=0.5,
		label="Iris-virginica (46.0/1.0)",
		pos="246.5,192",
		shape=box,
		style=filled,
		width=2.0139];
	N2 -> N8	 [label="> 1.7",
		lp="238.5,235.5",
		pos="e,236.47,210.05 206.38,261.21 213.45,249.18 223.12,232.75 231.19,219.03"];
	N4	 [height=0.5,
		label="Iris-versicolor (48.0/1.0)",
		pos="75.5,105",
		shape=box,
		style=filled,
		width=2.0972];
	N3 -> N4	 [label="<= 4.9",
		lp="111.5,148.5",
		pos="e,81.562,123.18 99.429,173.8 95.281,162.05 89.702,146.24 84.974,132.84"];
	N5	 [height=0.5,
		label=petalwidth,
		pos="217.5,105",
		width=1.336];
	N3 -> N5	 [label="> 4.9",
		lp="183.5,148.5",
		pos="e,197.09,121.49 126.04,175.41 143.72,161.99 169.42,142.49 189.07,127.57"];
	N6	 [height=0.5,
		label="Iris-virginica (3.0)",
		pos="142.5,18",
		shape=box,
		style=filled,
		width=1.625];
	N5 -> N6	 [label="<= 1.5",
		lp="203.5,61.5",
		pos="e,157.69,36.214 203.04,87.611 192.15,75.271 177.03,58.136 164.63,44.077"];
	N7	 [height=0.5,
		label="Iris-versicolor (3.0/1.0)",
		pos="291.5,18",
		shape=box,
		style=filled,
		width=2];
	N5 -> N7	 [label="> 1.5",
		lp="273.5,61.5",
		pos="e,276.51,36.214 231.77,87.611 242.51,75.271 257.43,58.136 269.67,44.077"];
}

```

**Comment by fracpete** [comment]
Remove the .props that you created.

**Comment by rsalvini** [comment]
I'm doing the tests on other machine which I didn't create the .props

**Comment by fracpete** [comment]
Can you confirm that it doesn't work with an Oracle JDK/JRE?

**Comment by rsalvini** [comment]
Yes, the same problem occurs with Oracle Java.

**Comment by fracpete** [comment]
The problem was due to Weka's new package loading mechanism: the .props file of the package didn't get loaded and therefore the PNG output format (`-Tpng`) wasn't set, resulting in just the default dotty output. Loading of dotty file as PNG failed of course. New version will require Weka 3.9.1.

**Comment by rsalvini** [comment]
ok, I guess I'll have to wait for the stable version of Weka 3.9.1 to use the visualize then...
thank you for your help

**Comment by fracpete** [comment]
Weka 3.9.1 has already been available for some time.

**Comment by fracpete** [comment]
A quick fix for the old version would be to add:
```
AdditionalOptions=-Tpng
```
to the props file.

**Comment by rsalvini** [comment]
I followed the quick fix you suggested and now the visualizer is working! :)
Thank you for you attention.
Bests.

P.S.: Weka version 3-9-1 is the developer version and I'd rather use the stable version.

**Comment by fracpete** [comment]
Both branches are stable. 3.8.x is tied to the latest version of the Data Mining book and only gets bugfixes, but no new features. Developer version receives new features.
